### ISSUE TITLE
User Story 1: Products list

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/reifenverwaltung#1]

**Comment by ella-blaupause** [comment]
## Display products list

## Value proposition

As a user
I want to see a list of product
So that I can get an overview of the offer


## Description



![Image](https://github.com/ella-blaupause/reifenverwaltung/assets/124199994/70a7887e-340d-4174-826b-b35a7cf1e636)




## Acceptance criteria

- [x] Name of the product is displayed
- [x] Photo is displayed
- [x] "Reifenbreite", "Breite/Höhe" and "Durchmesser" is displayed
- [x]  Season ("Sommer-", "Winter" or "Ganzjahresreifen") is specified

## Tasks

- [x] Create a new branch
- [x] Create dummy data
- [x] display data in a list

## Complexity

M

**Comment by ella-blaupause** [comment]
done
