### ISSUE TITLE
User Story 2: Customer portal

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/reifenverwaltung#2]

**Comment by ella-blaupause** [comment]
## Create a customer portal

## Value proposition

As a customer
I would like to have a separate portal
So that I can get helpful information as a potential buyer 


## Description


![Image](https://github.com/ella-blaupause/reifenverwaltung/assets/124199994/8d8f5f51-845f-405a-ae3a-b57ef98b5a7d)



## Acceptance criteria

- [x] A button with the text "Kundenbereich" is displayed
- [x]  Clicking the button, you will be taken to the page with the products


## Tasks

- [x] Create a new branch
- [x] Create a button
- [x] Create a new page for customer portal

## Complexity

S
