### ISSUE TITLE
User Story 3: Database

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/reifenverwaltung#3]

**Comment by ella-blaupause** [comment]
## Create a database with MongoDB

## Value proposition

As a developer
I would like create a database
So that I can better manage the data


## Description




## Acceptance criteria

- [x] Productlist is displayed from database



## Tasks

- [x] Create a new branch
- [x] Create a cluster in MongoDB
- [x] Conect homepage with database

## Complexity

L
