### ISSUE TITLE
User Story 4: Customer Login

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/reifenverwaltung#4]

**Comment by ella-blaupause** [comment]
## Create a customer login

## Value proposition

As a developer
I would like create a customer login
So that I have an overview of potential customers


## Description

![Image](https://github.com/ella-blaupause/reifenverwaltung/assets/124199994/758607dc-66c9-4973-8025-988822aedcf6)


## Acceptance criteria

- [x] Clicking on the "Kundenbereich" button directs you to the customer login page
   - [x] Form is displayed with
      - [x] Input field for "Benutzername"
      - [x] Input field for "Passwort"
   - [x] login-button is displayed
   - [x] Clicking on the "login" button directs you to the product page
   - [x] "Neuer Account" link is displayed

## Tasks

- [x] Create a new branch
- [x] Create a cluster in MongoDB user data
- [x] Conect homepage with user database

## Complexity

XL
