### ISSUE TITLE
User Story 5: Customer Register

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/reifenverwaltung#5]

**Comment by ella-blaupause** [comment]
## Create a customer register

## Value proposition

As a developer
I would like create a customer register
So that I can add a new customers


## Description


![Image](https://github.com/ella-blaupause/reifenverwaltung/assets/124199994/2e585c75-595d-4508-bd1d-f8884291d27e)



## Acceptance criteria

- [ ] Clicking on the "Neuer Account" Link takes you to the customer register page 
   - [ ] Form is displayed with
      - [ ] Input for "Benutzername"
      - [ ] Input for "Passwort"
   - [ ] "erstellen"-button is displayed
   - [ ] Clicking on the "erstellen" button create a new accound and takes you to the customer login page 
   - [ ] "löschen"-button is displayed

## Tasks


- [ ] Create a new branch
- [ ] Create a cluster in MongoDB user data
- [ ] Conect homepage with user database

## Complexity

XL
