### ISSUE TITLE
User Story 6: Admin

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/reifenverwaltung#6]

**Comment by ella-blaupause** [comment]
## Create an admin 

## Value proposition

As a developer
I would like create a admin page
So that the admin can edit the list without the developer


## Description



![Image](https://github.com/ella-blaupause/reifenverwaltung/assets/124199994/9f03d446-7b4f-4c6e-86f6-98453f9ffa19)



## Acceptance criteria

- [ ] Clicking on the "admin" button directs you to the admin  page
- [ ] When I am logged in, I can see if I am an admin.
- [ ] Link to admin page is displayed

## Tasks

- [ ] Create a new branch
- [ ] Create a cluster in MongoDB admin data


## Complexity

XL
